// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by the Game Data Editor.
// 
//      Changes to this file will be lost if the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using UnityEngine;
using System;
using System.Collections.Generic;

using GameDataEditor;

namespace GameDataEditor
{
    public class GDETwoDListCustomData : IGDEData
    {
        private static string asdKey = "asd";
		public List<string>      asd;
		public void Set_asd()
        {
	        GDEDataManager.SetStringList(_key+"_"+asdKey, asd);
		}
		

        public GDETwoDListCustomData()
		{
			_key = string.Empty;
		}

		public GDETwoDListCustomData(string key)
		{
			_key = key;
		}
		
        public override void LoadFromDict(string dataKey, Dictionary<string, object> dict)
        {
            _key = dataKey;
			
			if (dict == null)
				LoadFromSavedData(dataKey);
			else
			{
                dict.TryGetStringList(asdKey, out asd);
                LoadFromSavedData(dataKey);
			}
		}

        public override void LoadFromSavedData(string dataKey)
		{
			_key = dataKey;
			
            asd = GDEDataManager.GetStringList(_key+"_"+asdKey, asd);
         }

        public void Reset_asd()
        {
	        GDEDataManager.ResetToDefault(_key, asdKey);
	        
	        Dictionary<string, object> dict;
	        GDEDataManager.Get(_key, out dict);
	        dict.TryGetStringList(asdKey, out asd);
        }
		

        public void ResetAll()
        {
            GDEDataManager.ResetToDefault(_key, asdKey);


            Dictionary<string, object> dict;
            GDEDataManager.Get(_key, out dict);
            LoadFromDict(_key, dict);
        }
    }
}
