// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by the Game Data Editor.
// 
//      Changes to this file will be lost if the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using UnityEngine;
using System;

namespace GameDataEditor
{
    public class GDEReadSceneItemKeys
    {
        public static string ReadScene_test_data = "test_data";
        public static string ReadSceneCustom_custom_data_1 = "custom_data_1";
        public static string ReadSceneCustom_custom_data_2 = "custom_data_2";
        public static string ReadSceneCustom_custom_data_3 = "custom_data_3";
    }
}