// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by the Game Data Editor.
// 
//      Changes to this file will be lost if the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using UnityEngine;
using System;

namespace GameDataEditor
{
    public class GDEItemKeys
    {
        public static string characterList_char_0 = "char_0";
        public static string characterList_char_1 = "char_1";
        public static string characterList_char_2 = "char_2";
        public static string characterList_char_3 = "char_3";
        public static string characterList_char_4 = "char_4";
        public static string characterList_char_5 = "char_5";
        public static string characterList_char_6 = "char_6";
        public static string characterList_char_7 = "char_7";
        public static string characterList_char_8 = "char_8";
        public static string characterList_char_9 = "char_9";
        public static string characterList_char_10 = "char_10";
        public static string characterList_char_11 = "char_11";
        public static string characterList_char_12 = "char_12";
        public static string characterList_char_13 = "char_13";
        public static string characterList_char_14 = "char_14";
        public static string characterList_char_15 = "char_15";
        public static string characterList_char_16 = "char_16";
        public static string characterList_char_17 = "char_17";
        public static string characterList_char_18 = "char_18";
        public static string characterList_char_19 = "char_19";
        public static string characterList_char_20 = "char_20";
        public static string characterList_char_21 = "char_21";
        public static string characterList_char_22 = "char_22";
        public static string characterList_char_23 = "char_23";
        public static string characterList_char_24 = "char_24";
        public static string characterList_char_25 = "char_25";
        public static string characterList_char_26 = "char_26";
        public static string characterList_char_27 = "char_27";
        public static string characterList_char_28 = "char_28";
        public static string characterList_char_29 = "char_29";
        public static string characterList_char_30 = "char_30";
        public static string characterList_char_31 = "char_31";
        public static string characterList_char_32 = "char_32";
        public static string characterList_char_33 = "char_33";
        public static string characterList_char_34 = "char_34";
        public static string characterList_char_35 = "char_35";
        public static string characterList_char_36 = "char_36";
        public static string characterList_char_37 = "char_37";
        public static string characterList_char_38 = "char_38";
        public static string characterList_char_39 = "char_39";
        public static string characterList_char_40 = "char_40";
        public static string characterList_char_41 = "char_41";
        public static string characterList_char_42 = "char_42";
        public static string characterList_char_43 = "char_43";
        public static string characterList_char_44 = "char_44";
        public static string characterList_char_45 = "char_45";
        public static string characterList_char_46 = "char_46";
        public static string characterList_char_47 = "char_47";
        public static string characterList_char_48 = "char_48";
        public static string characterList_char_49 = "char_49";
        public static string characterList_char_50 = "char_50";
        public static string characterList_char_51 = "char_51";
        public static string characterList_char_52 = "char_52";
        public static string characterList_char_53 = "char_53";
        public static string characterList_char_54 = "char_54";
        public static string characterList_char_55 = "char_55";
        public static string characterList_char_56 = "char_56";
        public static string characterList_char_57 = "char_57";
        public static string characterList_char_58 = "char_58";
        public static string characterList_char_59 = "char_59";
        public static string characterList_char_60 = "char_60";
        public static string characterList_char_61 = "char_61";
        public static string characterList_char_62 = "char_62";
        public static string characterList_char_63 = "char_63";
        public static string characterList_char_64 = "char_64";
        public static string characterList_char_65 = "char_65";
        public static string characterList_char_66 = "char_66";
        public static string characterList_char_67 = "char_67";
        public static string characterList_char_68 = "char_68";
        public static string characterList_char_69 = "char_69";
        public static string characterList_char_70 = "char_70";
        public static string characterList_char_71 = "char_71";
        public static string characterList_char_72 = "char_72";
        public static string characterList_char_73 = "char_73";
        public static string characterList_char_74 = "char_74";
        public static string characterList_char_75 = "char_75";
        public static string characterList_char_76 = "char_76";
        public static string characterList_char_77 = "char_77";
        public static string missionList_mission_0 = "mission_0";
        public static string missionList_mission_1 = "mission_1";
        public static string missionList_mission_2 = "mission_2";
        public static string missionList_mission_3 = "mission_3";
        public static string missionList_mission_4 = "mission_4";
        public static string missionList_mission_5 = "mission_5";
        public static string missionList_mission_6 = "mission_6";
        public static string missionLocalize_missionLocal_0 = "missionLocal_0";
        public static string missionLocalize_missionLocal_1 = "missionLocal_1";
        public static string missionLocalize_missionLocal_2 = "missionLocal_2";
        public static string missionLocalize_missionLocal_3 = "missionLocal_3";
        public static string missionLocalize_missionLocal_4 = "missionLocal_4";
        public static string missionLocalize_missionLocal_5 = "missionLocal_5";
        public static string missionLocalize_missionLocal_6 = "missionLocal_6";
        public static string buffList_buff_0 = "buff_0";
        public static string buffList_buff_1 = "buff_1";
        public static string buffList_buff_2 = "buff_2";
        public static string buffList_buff_3 = "buff_3";
        public static string buffList_buff_4 = "buff_4";
        public static string buffList_buff_5 = "buff_5";
        public static string buffList_buff_6 = "buff_6";
        public static string spinList_spin_0 = "spin_0";
        public static string spinList_spin_1 = "spin_1";
        public static string spinList_spin_2 = "spin_2";
        public static string spinList_spin_3 = "spin_3";
        public static string spinList_spin_4 = "spin_4";
        public static string spinList_spin_5 = "spin_5";
        public static string spinList_spin_6 = "spin_6";
        public static string spinList_spin_7 = "spin_7";
    }
}